version: '3.1'

services:
  users-service-database:
    image: postgres:11.5
    ports:
      - "3259:5432"
    command: postgres -c fsync=off
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
